from pathlib import Path
import sys
root=Path(sys.argv[1])
p=root/'app/build.gradle.kts'
s=p.read_text()
s=s.replace('versionCode = 34','versionCode = 35').replace('versionName = \"0.9.1\"','versionName = \"0.9.2\"')
p.write_text(s)
p=root/'app/src/main/java/kz/kairat/organizer/AppStrings.kt'
s=p.read_text()
s=s.replace('val supportedLanguages = listOf(\"ru\",\"kk\",\"en\",\"zh\",\"de\",\"es\",\"fr\",\"tr\")','val supportedLanguages = listOf(\"kk\",\"ru\",\"en\",\"zh\",\"de\",\"es\",\"fr\",\"tr\")')
s=s.replace('0.9.1 (34)','0.9.2 (35)')
p.write_text(s)
p=root/'app/src/main/java/kz/kairat/organizer/Theme.kt'
s=p.read_text()
theme_old='private val Light = lightColorScheme(primary=Color(0xFF0B5A7A),secondary=Color(0xFF0AA7C8),tertiary=Color(0xFFE7B84A),surface=Color(0xFFF8FAFC))\nprivate val Dark = darkColorScheme(primary=Color(0xFF5BC7E6),secondary=Color(0xFF27B7D5),tertiary=Color(0xFFF0C55B),surface=Color(0xFF050607),background=Color.Black)'
theme_new='private val Light = lightColorScheme(\n    primary=Color(0xFF0A84D8), onPrimary=Color.White,\n    primaryContainer=Color(0xFFD9F2FF), onPrimaryContainer=Color(0xFF082D42),\n    secondary=Color(0xFF009FD6), onSecondary=Color.White,\n    secondaryContainer=Color(0xFFCDEFFF), onSecondaryContainer=Color(0xFF063146),\n    tertiary=Color(0xFFFFD43B), onTertiary=Color(0xFF17324A),\n    tertiaryContainer=Color(0xFFFFF1A8), onTertiaryContainer=Color(0xFF3E3200),\n    background=Color(0xFFF4FBFF), surface=Color(0xFFF8FDFF),\n    surfaceVariant=Color(0xFFE3F5FD), outline=Color(0xFF70AFCB)\n)\nprivate val Dark = darkColorScheme(\n    primary=Color(0xFF5AC8FA), onPrimary=Color(0xFF002E46),\n    primaryContainer=Color(0xFF0A4968), onPrimaryContainer=Color(0xFFD5F3FF),\n    secondary=Color(0xFF45C8F2), onSecondary=Color(0xFF003544),\n    secondaryContainer=Color(0xFF123C50), onSecondaryContainer=Color(0xFFD0F2FF),\n    tertiary=Color(0xFFFFD54F), onTertiary=Color(0xFF3D3100),\n    tertiaryContainer=Color(0xFF5A4700), onTertiaryContainer=Color(0xFFFFED9A),\n    background=Color(0xFF06151D), surface=Color(0xFF081A23),\n    surfaceVariant=Color(0xFF102D3A), outline=Color(0xFF5C8EA5)\n)'
assert theme_old in s, 'Theme pattern not found'
p.write_text(s.replace(theme_old,theme_new))
p=root/'app/src/main/java/kz/kairat/organizer/OrganizerUi.kt'
s=p.read_text()
s=s.replace('Surface(color=Color(0xFF0B4B6B),shadowElevation=2.dp){','Surface(color=MaterialTheme.colorScheme.primary,shadowElevation=2.dp){')
s=s.replace('Surface(tonalElevation=3.dp,shadowElevation=3.dp,modifier=Modifier.fillMaxWidth().navigationBarsPadding()){','Surface(color=MaterialTheme.colorScheme.secondaryContainer,tonalElevation=3.dp,shadowElevation=3.dp,modifier=Modifier.fillMaxWidth().navigationBarsPadding()){')
s=s.replace('OutlinedTextField(q,{q=it},Modifier.fillMaxWidth(),leadingIcon={Icon(Icons.Default.Search,null)},placeholder={Text(AppStrings.t(lang,\"search\"))},singleLine=true)','OutlinedTextField(q,{q=it},Modifier.fillMaxWidth(),leadingIcon={Icon(Icons.Default.Search,null)},placeholder={Text(AppStrings.t(lang,\"search\"))},singleLine=true,colors=OutlinedTextFieldDefaults.colors(focusedContainerColor=MaterialTheme.colorScheme.primaryContainer,unfocusedContainerColor=MaterialTheme.colorScheme.primaryContainer))')
s=s.replace('items(notes,key={it.id}){n->Card(Modifier.fillMaxWidth().clickable{onOpen(n.id)}){','items(notes,key={it.id}){n->Card(Modifier.fillMaxWidth().clickable{onOpen(n.id)},colors=brandCardColors((n.id%2).toInt())){')
s=s.replace('Card(Modifier.fillMaxWidth().clickable{onOpen(p.id)}){','Card(Modifier.fillMaxWidth().clickable{onOpen(p.id)},colors=brandCardColors((p.id%2).toInt())){')
s=s.replace('else items(journal,key={it.id}){j->Card(Modifier.fillMaxWidth()){','else items(journal,key={it.id}){j->Card(Modifier.fillMaxWidth(),colors=brandCardColors(2)){')
s=s.replace('else items(linked,key={it.id}){n->Card(Modifier.fillMaxWidth()){','else items(linked,key={it.id}){n->Card(Modifier.fillMaxWidth(),colors=brandCardColors(1)){')
s=s.replace('items(stages,key={it.id}){st->Card(Modifier.fillMaxWidth()){','items(stages,key={it.id}){st->Card(Modifier.fillMaxWidth(),colors=brandCardColors((st.id%2).toInt())){')
s=s.replace('Card(Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){ProjectMoneySummaryRow','Card(Modifier.fillMaxWidth(),colors=brandCardColors(0)){Column(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){ProjectMoneySummaryRow',1)
s=s.replace('items(available,key={it.id}){n->Card(Modifier.fillMaxWidth().clickable{db.linkNoteToProject(projectId,n.id);onChanged()}){','items(available,key={it.id}){n->Card(Modifier.fillMaxWidth().clickable{db.linkNoteToProject(projectId,n.id);onChanged()},colors=brandCardColors((n.id%2).toInt())){')
s=s.replace('amountColor=MaterialTheme.colorScheme.primary,\n                    onDelete=','amountColor=MaterialTheme.colorScheme.primary,\n                    cardTone=0,\n                    onDelete=')
s=s.replace('amountColor=MaterialTheme.colorScheme.error,\n                    onDelete=','amountColor=MaterialTheme.colorScheme.error,\n                    cardTone=1,\n                    onDelete=')
s=s.replace('Card(\n                Modifier.fillMaxWidth().clickable{balanceExpanded=!balanceExpanded}\n            ){','Card(\n                Modifier.fillMaxWidth().clickable{balanceExpanded=!balanceExpanded},\n                colors=brandCardColors(2)\n            ){')
s=s.replace('@Composable private fun MoneyColumn(title:String,entries:List<MoneyEntry>,lang:String,modifier:Modifier=Modifier,amountColor:Color,onDelete:(Long)->Unit){','@Composable private fun MoneyColumn(title:String,entries:List<MoneyEntry>,lang:String,modifier:Modifier=Modifier,amountColor:Color,cardTone:Int,onDelete:(Long)->Unit){')
s=s.replace('items(entries,key={it.id}){m->MoneyEntryCard(m,lang,amountColor,onDelete)}','items(entries,key={it.id}){m->MoneyEntryCard(m,lang,amountColor,cardTone,onDelete)}')
s=s.replace('@Composable private fun MoneyEntryCard(m:MoneyEntry,lang:String,amountColor:Color,onDelete:(Long)->Unit){\n    Card(Modifier.fillMaxWidth()){','@Composable private fun MoneyEntryCard(m:MoneyEntry,lang:String,amountColor:Color,cardTone:Int,onDelete:(Long)->Unit){\n    Card(Modifier.fillMaxWidth(),colors=brandCardColors(cardTone)){')
s=s.replace('OutlinedButton(onClick={languageMenu=true}){','FilledTonalButton(onClick={languageMenu=true},colors=ButtonDefaults.filledTonalButtonColors(containerColor=MaterialTheme.colorScheme.tertiary,contentColor=MaterialTheme.colorScheme.onTertiary)){')
s=s.replace('@Composable private fun SettingsCard(title:String,content: @Composable ColumnScope.() -> Unit){Card(Modifier.fillMaxWidth()){','@Composable private fun SettingsCard(title:String,content: @Composable ColumnScope.() -> Unit){Card(Modifier.fillMaxWidth(),colors=brandCardColors(0)){')
s=s.replace('@Composable private fun organizerTopBarColors()=TopAppBarDefaults.topAppBarColors(containerColor=Color(0xFF0B4B6B),titleContentColor=Color.White,navigationIconContentColor=Color.White,actionIconContentColor=Color.White)','@Composable private fun brandCardColors(tone:Int=0)=CardDefaults.cardColors(containerColor=when(tone%3){0->MaterialTheme.colorScheme.primaryContainer;1->MaterialTheme.colorScheme.tertiaryContainer;else->MaterialTheme.colorScheme.secondaryContainer})\n@Composable private fun organizerTopBarColors()=TopAppBarDefaults.topAppBarColors(containerColor=MaterialTheme.colorScheme.primary,titleContentColor=Color.White,navigationIconContentColor=Color.White,actionIconContentColor=Color.White)')
s=s.replace('item{Card(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){','item{Card(Modifier.fillMaxWidth(),colors=brandCardColors(0)){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){',1)
s=s.replace('Card(Modifier.fillMaxWidth()){\n            Box(Modifier.fillMaxWidth().height(46.dp)','Card(Modifier.fillMaxWidth(),colors=brandCardColors(cardTone)){\n            Box(Modifier.fillMaxWidth().height(46.dp)',1)
assert '@Composable private fun TopActionPill(text:String,icon:androidx.compose.ui.graphics.vector.ImageVector,onClick:()->Unit){\n    FilledTonalButton(onClick=onClick,shape=RoundedCornerShape(17.dp),contentPadding=PaddingValues(horizontal=10.dp,vertical=0.dp),modifier=Modifier.heightIn(min=34.dp,max=38.dp)){' in s, 'TopActionPill pattern not found'
s=s.replace('@Composable private fun TopActionPill(text:String,icon:androidx.compose.ui.graphics.vector.ImageVector,onClick:()->Unit){\n    FilledTonalButton(onClick=onClick,shape=RoundedCornerShape(17.dp),contentPadding=PaddingValues(horizontal=10.dp,vertical=0.dp),modifier=Modifier.heightIn(min=34.dp,max=38.dp)){','@Composable private fun TopActionPill(text:String,icon:androidx.compose.ui.graphics.vector.ImageVector,onClick:()->Unit){\n    FilledTonalButton(onClick=onClick,shape=RoundedCornerShape(17.dp),colors=ButtonDefaults.filledTonalButtonColors(containerColor=MaterialTheme.colorScheme.tertiary,contentColor=MaterialTheme.colorScheme.onTertiary),contentPadding=PaddingValues(horizontal=10.dp,vertical=0.dp),modifier=Modifier.heightIn(min=34.dp,max=38.dp)){')
s=s.replace('if(selected) Button(onClick=onClick,shape=shape,contentPadding=PaddingValues(horizontal=5.dp,vertical=0.dp),modifier=modifier.heightIn(min=40.dp,max=44.dp),content=content)\n    else OutlinedButton(onClick=onClick,shape=shape,contentPadding=PaddingValues(horizontal=5.dp,vertical=0.dp),modifier=modifier.heightIn(min=40.dp,max=44.dp),content=content)','if(selected) Button(onClick=onClick,shape=shape,colors=ButtonDefaults.buttonColors(containerColor=MaterialTheme.colorScheme.tertiary,contentColor=MaterialTheme.colorScheme.onTertiary),contentPadding=PaddingValues(horizontal=5.dp,vertical=0.dp),modifier=modifier.heightIn(min=40.dp,max=44.dp),content=content)\n    else OutlinedButton(onClick=onClick,shape=shape,colors=ButtonDefaults.outlinedButtonColors(contentColor=MaterialTheme.colorScheme.primary),contentPadding=PaddingValues(horizontal=5.dp,vertical=0.dp),modifier=modifier.heightIn(min=40.dp,max=44.dp),content=content)',1)
s=s.replace('if(selected) Button(onClick=onClick,shape=shape,contentPadding=PaddingValues(0.dp),modifier=modifier.heightIn(min=40.dp,max=44.dp),content=content)\n    else OutlinedButton(onClick=onClick,shape=shape,contentPadding=PaddingValues(0.dp),modifier=modifier.heightIn(min=40.dp,max=44.dp),content=content)','if(selected) Button(onClick=onClick,shape=shape,colors=ButtonDefaults.buttonColors(containerColor=MaterialTheme.colorScheme.tertiary,contentColor=MaterialTheme.colorScheme.onTertiary),contentPadding=PaddingValues(0.dp),modifier=modifier.heightIn(min=40.dp,max=44.dp),content=content)\n    else OutlinedButton(onClick=onClick,shape=shape,colors=ButtonDefaults.outlinedButtonColors(contentColor=MaterialTheme.colorScheme.primary),contentPadding=PaddingValues(0.dp),modifier=modifier.heightIn(min=40.dp,max=44.dp),content=content)',1)
p.write_text(s)
p=root/'app/src/main/res/values/styles.xml'
p.write_text(p.read_text().replace('#0B4B6B','#0A84D8'))
old_icon=root/'app/src/main/res/drawable/ic_app_icon_approved.webp'
if old_icon.exists(): old_icon.unlink()
(root/'app/src/main/res/drawable/ic_app_icon_approved.xml').write_text('<?xml version="1.0" encoding="utf-8"?>\n<vector xmlns:android="http://schemas.android.com/apk/res/android"\n    android:width="108dp" android:height="108dp"\n    android:viewportWidth="108" android:viewportHeight="108">\n    <path android:fillColor="#35BDEB" android:pathData="M22,6 H86 Q102,6 102,22 V86 Q102,102 86,102 H22 Q6,102 6,86 V22 Q6,6 22,6 Z"/>\n    <path android:fillColor="#0A84D8" android:pathData="M12,67 C27,91 58,102 91,96 C99,94 102,88 102,82 V86 Q102,102 86,102 H22 Q6,102 6,86 V67 Z"/>\n    <path android:fillColor="#FFFFFF" android:pathData="M28,24 H68 Q76,24 76,32 V78 Q76,86 68,86 H28 Q20,86 20,78 V32 Q20,24 28,24 Z"/>\n    <path android:fillColor="#0B78B9" android:pathData="M29,39 H61 V43 H29 Z M29,50 H61 V54 H29 Z M29,61 H56 V65 H29 Z M29,72 H50 V76 H29 Z"/>\n    <path android:fillColor="#0A84D8" android:pathData="M16,33 H27 Q30,33 30,36 Q30,39 27,39 H16 Q13,39 13,36 Q13,33 16,33 Z M16,46 H27 Q30,46 30,49 Q30,52 27,52 H16 Q13,52 13,49 Q13,46 16,46 Z M16,59 H27 Q30,59 30,62 Q30,65 27,65 H16 Q13,65 13,62 Q13,59 16,59 Z M16,72 H27 Q30,72 30,75 Q30,78 27,78 H16 Q13,78 13,75 Q13,72 16,72 Z"/>\n    <path android:fillColor="#FFD43B" android:pathData="M74,20 L88,26 L63,84 L49,78 Z"/>\n    <path android:fillColor="#F3B600" android:pathData="M49,78 L63,84 L52,91 Z"/>\n    <path android:fillColor="#FFF3A0" android:pathData="M76,24 L81,26 L57,81 L52,79 Z"/>\n    <path android:fillColor="#0A84D8" android:pathData="M69,31 L83,37 L81,42 L67,36 Z"/>\n</vector>\n')
assert 'versionCode = 35' in (root/'app/build.gradle.kts').read_text()
assert 'val supportedLanguages = listOf(\"kk\",\"ru\",\"en\",\"zh\",\"de\",\"es\",\"fr\",\"tr\")' in (root/'app/src/main/java/kz/kairat/organizer/AppStrings.kt').read_text()
